version: '3.9'

services:
  library-api:
    image: project/library-api
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "50050:80"
    networks:
      - project





networks:
  project:
    name: project-stream
