name: CI

on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

env:
  MAIN_PYTHON_VERSION: '3.10'
  LIBRARY_NAME: '{{ cookiecutter.__pkg_namespace | replace(".", "-") }}'
  LIBRARY_NAMESPACE: '{{ cookiecutter.__pkg_namespace }}'

concurrency:
  group: {{ '${{ github.workflow }}-${{ github.ref }}' }}
  cancel-in-progress: true

jobs:

  tests:
    name: "Build package"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: {{ '${{ env.MAIN_PYTHON_VERSION }}' }}

      - name: "Install the library"
        run: |
          python -m pip install .

      - name: "Test import"
        run: |
          {{ 'python -c "from ${{ env.LIBRARY_NAMESPACE }} import __version__; print(__version__)"' }}

  build-library:
    name: "Build library"
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: ansys/actions/build-library@v4
        with:
          library-name: {{ '${{ env.LIBRARY_NAME }}' }}

  release:
    name: "Release library"
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    needs: build-package
    runs-on: ubuntu-latest
    steps:

      - name: "Release to the private PyPI"
        uses: ansys/actions/release-pypi-private@v4
        with:
          library-name: {{ '${{ env.LIBRARY_NAME }}' }}
          twine-username: "__token__"
          twine-token: {{ '${{ secrets.PYANSYS_PYPI_PRIVATE_PAT }}' }}

      - name: "Release to GitHub"
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            {{ '${{ env.LIBRARY_NAME }}-artifacts/*.whl }}' }}
            {{ '${{ env.LIBRARY_NAME }}-artifacts/*.tar.gz' }}
